// Field configs drive the generic admin ResourceManager.
const LEVELS = ["Beginner", "Intermediate", "Advanced"];
const MODES = ["Online", "Classroom", "Online / Classroom", "Hybrid"];
const BATCH_STATUS = ["Upcoming", "Filling Fast", "Started", "Completed", "Cancelled"];
const FAQ_CATS = ["Courses", "Fees", "Batches", "Certification", "Placement", "Training"];
const GALLERY_CATS = ["Student Activities", "Student Placements", "Placement Celebrations", "Certificate Distribution", "Course Completion", "Annual Events", "Seminars", "Workshops", "Technical Events", "Classroom Activities", "Industrial Visits", "Team Events", "Other"];
const VIDEO_CATS = ["Placements", "Workshops", "Seminars", "Institute Events", "Student Activities", "Other"];
const EVENT_CATS = ["Seminar", "Workshop", "Webinar", "Career Guidance", "Placement Drive", "Technical Event", "Annual Celebration", "Certificate Distribution", "Course Completion Ceremony"];
const THEME_TYPES = ["time_based", "seasonal", "festival", "event", "admission_campaign", "custom"];

export const RESOURCES = {
  courses: {
    title: "Courses", singular: "Course", titleField: "name",
    columns: [["name", "Name"], ["category", "Category"], ["level", "Level"], ["fee", "Fee"], ["featured", "Featured"], ["published", "Published"]],
    fields: [
      { name: "name", label: "Course Name", type: "text" },
      { name: "category", label: "Category", type: "text" },
      { name: "short_description", label: "Short Description", type: "textarea", full: true },
      { name: "full_description", label: "Full Description", type: "textarea", rows: 5, full: true },
      { name: "image_url", label: "Course Image", type: "image" },
      { name: "duration", label: "Duration", type: "text" },
      { name: "level", label: "Level", type: "select", options: LEVELS },
      { name: "mode", label: "Training Mode", type: "select", options: MODES },
      { name: "fee", label: "Fee (₹)", type: "number" },
      { name: "discounted_fee", label: "Discounted Fee (₹)", type: "number" },
      { name: "certification", label: "Certification", type: "text" },
      { name: "prerequisites", label: "Prerequisites", type: "textarea", full: true },
      { name: "learning_outcomes", label: "Learning Outcomes", type: "tags", full: true },
      { name: "career_opportunities", label: "Career Opportunities", type: "tags", full: true },
      { name: "tools", label: "Tools / Technologies", type: "tags", full: true },
      { name: "syllabus", label: "Syllabus (JSON)", type: "json", full: true, rows: 8, default: [{ module: "Module 1", topics: ["Topic 1"] }], hint: 'Format: [{"module":"Module 1","topics":["Topic 1","Topic 2"]}]' },
      { name: "featured", label: "Featured", type: "switch" },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { level: "Beginner", mode: "Online / Classroom", published: true, featured: false, syllabus: [] },
  },
  batches: {
    title: "Batches", singular: "Batch", titleField: "course_name",
    columns: [["course_name", "Course"], ["start_date", "Start"], ["trainer", "Trainer"], ["status", "Status"], ["seats", "Seats"], ["published", "Published"]],
    fields: [
      { name: "course_name", label: "Course Name", type: "text" },
      { name: "course_id", label: "Course ID (optional)", type: "text" },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
      { name: "days", label: "Days", type: "text" },
      { name: "time", label: "Time", type: "text" },
      { name: "trainer", label: "Trainer", type: "text" },
      { name: "mode", label: "Mode", type: "select", options: ["Online", "Classroom", "Hybrid"] },
      { name: "seats", label: "Available Seats", type: "number" },
      { name: "location", label: "Location", type: "text" },
      { name: "status", label: "Status", type: "select", options: BATCH_STATUS },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { status: "Upcoming", mode: "Online", published: true, seats: 30 },
  },
  trainers: {
    title: "Trainers", singular: "Trainer", titleField: "name", publishField: "active",
    columns: [["name", "Name"], ["designation", "Designation"], ["experience", "Experience"], ["active", "Active"]],
    fields: [
      { name: "name", label: "Name", type: "text" },
      { name: "designation", label: "Designation", type: "text" },
      { name: "experience", label: "Experience", type: "text" },
      { name: "photo_url", label: "Photo", type: "image" },
      { name: "skills", label: "Skills", type: "tags", full: true },
      { name: "certifications", label: "Certifications", type: "tags", full: true },
      { name: "bio", label: "Biography", type: "textarea", rows: 4, full: true },
      { name: "linkedin", label: "LinkedIn URL", type: "text" },
      { name: "active", label: "Active", type: "switch" },
    ],
    defaults: { active: true },
  },
  testimonials: {
    title: "Testimonials", singular: "Testimonial", titleField: "name",
    columns: [["name", "Student"], ["course", "Course"], ["rating", "Rating"], ["published", "Published"]],
    fields: [
      { name: "name", label: "Student Name", type: "text" },
      { name: "course", label: "Course", type: "text" },
      { name: "rating", label: "Rating (1-5)", type: "number" },
      { name: "text", label: "Testimonial", type: "textarea", rows: 4, full: true },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { rating: 5, published: true },
  },
  faqs: {
    title: "FAQs", singular: "FAQ", titleField: "question",
    columns: [["question", "Question"], ["category", "Category"], ["published", "Published"]],
    fields: [
      { name: "category", label: "Category", type: "select", options: FAQ_CATS },
      { name: "question", label: "Question", type: "text", full: true },
      { name: "answer", label: "Answer", type: "textarea", rows: 4, full: true },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { category: "Courses", published: true },
  },
  blog: {
    title: "Blog Posts", singular: "Article", titleField: "title",
    columns: [["title", "Title"], ["category", "Category"], ["author", "Author"], ["published", "Published"]],
    fields: [
      { name: "title", label: "Title", type: "text", full: true },
      { name: "category", label: "Category", type: "text" },
      { name: "author", label: "Author", type: "text" },
      { name: "image_url", label: "Featured Image", type: "image" },
      { name: "excerpt", label: "Excerpt", type: "textarea", full: true },
      { name: "content", label: "Content", type: "textarea", rows: 8, full: true },
      { name: "tags", label: "Tags", type: "tags", full: true },
      { name: "seo_title", label: "SEO Title", type: "text" },
      { name: "seo_description", label: "SEO Description", type: "text" },
      { name: "slug", label: "URL Slug (auto if empty)", type: "text" },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { author: "CloudWave Team", published: true },
  },
  gallery: {
    title: "Photo Gallery", singular: "Photo", titleField: "title",
    columns: [["title", "Title"], ["category", "Category"], ["year", "Year"], ["featured", "Featured"], ["published", "Published"]],
    fields: [
      { name: "image_url", label: "Image", type: "image" },
      { name: "title", label: "Title", type: "text" },
      { name: "category", label: "Category", type: "select", options: GALLERY_CATS },
      { name: "description", label: "Description", type: "textarea", full: true },
      { name: "event_name", label: "Event Name", type: "text" },
      { name: "year", label: "Year", type: "text" },
      { name: "event_date", label: "Event Date", type: "date" },
      { name: "location", label: "Location", type: "text" },
      { name: "featured", label: "Featured", type: "switch" },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { category: "Other", year: String(new Date().getFullYear()), published: true },
  },
  videos: {
    title: "Videos", singular: "Video", titleField: "title",
    columns: [["title", "Title"], ["category", "Category"], ["platform", "Platform"], ["published", "Published"]],
    fields: [
      { name: "title", label: "Title", type: "text", full: true },
      { name: "video_url", label: "Video URL (YouTube)", type: "text", full: true, hint: "Paste any YouTube or Shorts URL" },
      { name: "category", label: "Category", type: "select", options: VIDEO_CATS },
      { name: "platform", label: "Platform", type: "select", options: ["youtube", "instagram", "other"] },
      { name: "thumbnail_url", label: "Thumbnail (optional)", type: "image" },
      { name: "description", label: "Description", type: "textarea", full: true },
      { name: "featured", label: "Featured", type: "switch" },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { category: "Other", platform: "youtube", published: true },
  },
  events: {
    title: "Events", singular: "Event", titleField: "title",
    columns: [["title", "Title"], ["category", "Category"], ["event_date", "Date"], ["published", "Published"]],
    fields: [
      { name: "title", label: "Title", type: "text", full: true },
      { name: "category", label: "Category", type: "select", options: EVENT_CATS },
      { name: "cover_image", label: "Cover Image", type: "image" },
      { name: "description", label: "Description", type: "textarea", rows: 4, full: true },
      { name: "event_date", label: "Event Date", type: "date" },
      { name: "location", label: "Location", type: "text" },
      { name: "youtube_url", label: "YouTube URL", type: "text" },
      { name: "instagram_url", label: "Instagram URL", type: "text" },
      { name: "featured", label: "Featured", type: "switch" },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { category: "Workshop", published: true },
  },
  placements: {
    title: "Placement Stories", singular: "Placement", titleField: "student_name",
    columns: [["student_name", "Student"], ["company_name", "Company"], ["job_title", "Role"], ["placement_year", "Year"], ["published", "Published"]],
    fields: [
      { name: "student_name", label: "Student Name", type: "text" },
      { name: "student_photo", label: "Student Photo", type: "image" },
      { name: "company_name", label: "Company", type: "text" },
      { name: "company_logo", label: "Company Logo", type: "image" },
      { name: "job_title", label: "Job Title", type: "text" },
      { name: "course", label: "Course Completed", type: "text" },
      { name: "placement_year", label: "Placement Year", type: "text" },
      { name: "placement_date", label: "Placement Date", type: "date" },
      { name: "story", label: "Success Story", type: "textarea", rows: 4, full: true },
      { name: "linkedin_url", label: "LinkedIn URL", type: "text" },
      { name: "featured", label: "Featured", type: "switch" },
      { name: "published", label: "Published", type: "switch" },
    ],
    defaults: { placement_year: String(new Date().getFullYear()), published: true },
  },
  themes: {    title: "Themes", singular: "Theme", titleField: "name", publishField: "is_active",
    columns: [["name", "Name"], ["type", "Type"], ["priority", "Priority"], ["start_date", "Start"], ["end_date", "End"], ["is_active", "Active"]],
    fields: [
      { name: "name", label: "Theme Name", type: "text" },
      { name: "type", label: "Type", type: "select", options: THEME_TYPES },
      { name: "description", label: "Description", type: "text", full: true },
      { name: "start_date", label: "Start Date (empty = always)", type: "date" },
      { name: "end_date", label: "End Date (empty = always)", type: "date" },
      { name: "priority", label: "Priority (higher wins)", type: "number" },
      { name: "primary_color", label: "Primary Color (#hex)", type: "text" },
      { name: "secondary_color", label: "Secondary Color (#hex)", type: "text" },
      { name: "accent_color", label: "Accent Color (#hex)", type: "text" },
      { name: "banner_image", label: "Banner Image", type: "image" },
      { name: "announcement_text", label: "Announcement Banner Text", type: "textarea", full: true },
      { name: "cta_text", label: "CTA Text", type: "text" },
      { name: "cta_url", label: "CTA URL", type: "text" },
      { name: "animation_enabled", label: "Animations", type: "switch" },
      { name: "is_active", label: "Active", type: "switch" },
    ],
    defaults: { type: "festival", priority: 5, primary_color: "#1D4ED8", secondary_color: "#4F46E5", accent_color: "#F97316", is_active: false, animation_enabled: false },
  },
  certificates: {
    title: "Certificates", singular: "Certificate", titleField: "student_name",
    columns: [["certificate_id", "Certificate ID"], ["student_name", "Student"], ["course", "Course"], ["issue_date", "Issued"], ["grade", "Grade"], ["published", "Valid"]],
    fields: [
      { name: "certificate_id", label: "Certificate ID", type: "text", hint: "Unique ID printed on the certificate, e.g. CWT-2026-0001" },
      { name: "student_name", label: "Student Name", type: "text" },
      { name: "course", label: "Course Completed", type: "text" },
      { name: "issue_date", label: "Issue Date", type: "date" },
      { name: "grade", label: "Grade", type: "text" },
      { name: "published", label: "Valid / Verifiable", type: "switch" },
    ],
    defaults: { published: true },
  },
};

export const JSON_FIELDS = { courses: ["syllabus"] };
